# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tictactoe.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tictactoe.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ftictactoe.proto\"\"\n\x05\x42oard\x12\x19\n\x05tiles\x18\x01 \x03(\x0e\x32\n.TileState\"^\n\x04Game\x12\x15\n\x05\x62oard\x18\x01 \x01(\x0b\x32\x06.Board\x12\x1f\n\x0blast_player\x18\x02 \x01(\x0e\x32\n.TileState\x12\x1e\n\ngame_state\x18\x03 \x01(\x0e\x32\n.GameState\"3\n\x04Move\x12\x1a\n\x06player\x18\x01 \x01(\x0e\x32\n.TileState\x12\x0f\n\x07tile_id\x18\x02 \x01(\x05\"7\n\x0bGameAndMove\x12\x13\n\x04game\x18\x01 \x01(\x0b\x32\x05.Game\x12\x13\n\x04move\x18\x02 \x01(\x0b\x32\x05.Move*$\n\tTileState\x12\t\n\x05\x45MPTY\x10\x00\x12\x05\n\x01X\x10\x01\x12\x05\n\x01O\x10\x02*N\n\tGameState\x12\x14\n\x10WAITING_TO_START\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\t\n\x05X_WIN\x10\x02\x12\t\n\x05O_WIN\x10\x03\x12\x08\n\x04\x44RAW\x10\x04\x32\x31\n\x0bGameService\x12\"\n\x0b\x41ttemptMove\x12\x0c.GameAndMove\x1a\x05.Game2%\n\rPlayerService\x12\x14\n\x04Play\x12\x05.Game\x1a\x05.Moveb\x06proto3'
)

_TILESTATE = _descriptor.EnumDescriptor(
  name='TileState',
  full_name='TileState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMPTY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='O', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=261,
  serialized_end=297,
)
_sym_db.RegisterEnumDescriptor(_TILESTATE)

TileState = enum_type_wrapper.EnumTypeWrapper(_TILESTATE)
_GAMESTATE = _descriptor.EnumDescriptor(
  name='GameState',
  full_name='GameState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WAITING_TO_START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='X_WIN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='O_WIN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=299,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATE)

GameState = enum_type_wrapper.EnumTypeWrapper(_GAMESTATE)
EMPTY = 0
X = 1
O = 2
WAITING_TO_START = 0
RUNNING = 1
X_WIN = 2
O_WIN = 3
DRAW = 4



_BOARD = _descriptor.Descriptor(
  name='Board',
  full_name='Board',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tiles', full_name='Board.tiles', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=53,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board', full_name='Game.board', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_player', full_name='Game.last_player', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_state', full_name='Game.game_state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=149,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='Move.player', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tile_id', full_name='Move.tile_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=202,
)


_GAMEANDMOVE = _descriptor.Descriptor(
  name='GameAndMove',
  full_name='GameAndMove',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='GameAndMove.game', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move', full_name='GameAndMove.move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=259,
)

_BOARD.fields_by_name['tiles'].enum_type = _TILESTATE
_GAME.fields_by_name['board'].message_type = _BOARD
_GAME.fields_by_name['last_player'].enum_type = _TILESTATE
_GAME.fields_by_name['game_state'].enum_type = _GAMESTATE
_MOVE.fields_by_name['player'].enum_type = _TILESTATE
_GAMEANDMOVE.fields_by_name['game'].message_type = _GAME
_GAMEANDMOVE.fields_by_name['move'].message_type = _MOVE
DESCRIPTOR.message_types_by_name['Board'] = _BOARD
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['GameAndMove'] = _GAMEANDMOVE
DESCRIPTOR.enum_types_by_name['TileState'] = _TILESTATE
DESCRIPTOR.enum_types_by_name['GameState'] = _GAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Board = _reflection.GeneratedProtocolMessageType('Board', (_message.Message,), {
  'DESCRIPTOR' : _BOARD,
  '__module__' : 'tictactoe_pb2'
  # @@protoc_insertion_point(class_scope:Board)
  })
_sym_db.RegisterMessage(Board)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'tictactoe_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  })
_sym_db.RegisterMessage(Game)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), {
  'DESCRIPTOR' : _MOVE,
  '__module__' : 'tictactoe_pb2'
  # @@protoc_insertion_point(class_scope:Move)
  })
_sym_db.RegisterMessage(Move)

GameAndMove = _reflection.GeneratedProtocolMessageType('GameAndMove', (_message.Message,), {
  'DESCRIPTOR' : _GAMEANDMOVE,
  '__module__' : 'tictactoe_pb2'
  # @@protoc_insertion_point(class_scope:GameAndMove)
  })
_sym_db.RegisterMessage(GameAndMove)



_GAMESERVICE = _descriptor.ServiceDescriptor(
  name='GameService',
  full_name='GameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=379,
  serialized_end=428,
  methods=[
  _descriptor.MethodDescriptor(
    name='AttemptMove',
    full_name='GameService.AttemptMove',
    index=0,
    containing_service=None,
    input_type=_GAMEANDMOVE,
    output_type=_GAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESERVICE)

DESCRIPTOR.services_by_name['GameService'] = _GAMESERVICE


_PLAYERSERVICE = _descriptor.ServiceDescriptor(
  name='PlayerService',
  full_name='PlayerService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=430,
  serialized_end=467,
  methods=[
  _descriptor.MethodDescriptor(
    name='Play',
    full_name='PlayerService.Play',
    index=0,
    containing_service=None,
    input_type=_GAME,
    output_type=_MOVE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAYERSERVICE)

DESCRIPTOR.services_by_name['PlayerService'] = _PLAYERSERVICE

# @@protoc_insertion_point(module_scope)
