# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tictactoe_pb2 as tictactoe__pb2


class GameServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AttemptMove = channel.unary_unary(
        '/GameService/AttemptMove',
        request_serializer=tictactoe__pb2.GameAndMove.SerializeToString,
        response_deserializer=tictactoe__pb2.Game.FromString,
        )


class GameServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AttemptMove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AttemptMove': grpc.unary_unary_rpc_method_handler(
          servicer.AttemptMove,
          request_deserializer=tictactoe__pb2.GameAndMove.FromString,
          response_serializer=tictactoe__pb2.Game.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GameService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PlayerServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Play = channel.unary_unary(
        '/PlayerService/Play',
        request_serializer=tictactoe__pb2.Game.SerializeToString,
        response_deserializer=tictactoe__pb2.Move.FromString,
        )


class PlayerServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Play(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlayerServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Play': grpc.unary_unary_rpc_method_handler(
          servicer.Play,
          request_deserializer=tictactoe__pb2.Game.FromString,
          response_serializer=tictactoe__pb2.Move.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PlayerService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
